#!/usr/bin/env bash
# Get Railway Backend URL from your deployment
# This script helps you find your Railway backend URL

echo "========================================"
echo "Solar Energy - Deployment Helper"
echo "========================================"
echo ""
echo "Step 1: Find Your Railway Backend URL"
echo ""
echo "1. Go to https://railway.app"
echo "2. Click your project"
echo "3. Click the 'backend' service"
echo "4. Click the 'Settings' tab"
echo "5. Look for 'Domains' section"
echo "6. Copy the URL (e.g., https://solar-backend-production-xxxx.up.railway.app)"
echo ""
echo "========================================"
echo "Step 2: Set Environment Variable in Vercel"
echo ""
echo "1. Go to https://vercel.com"
echo "2. Open your project"
echo "3. Click 'Settings' → 'Environment Variables'"
echo "4. Add new variable:"
echo "   Name:  VITE_API_URL"
echo "   Value: https://your-railway-url.up.railway.app"
echo ""
echo "   *** IMPORTANT: NO trailing slash ***"
echo "   ✓  Good: https://solar-backend-production.up.railway.app"
echo "   ✗  Bad:  https://solar-backend-production.up.railway.app/"
echo ""
echo "5. Select environments: Production, Preview, Development"
echo "6. Click 'Save'"
echo "7. Vercel will redeploy automatically"
echo ""
echo "========================================"
echo "Step 3: Verify It Works"
echo ""
echo "1. Visit your Vercel URL: https://your-app.vercel.app"
echo "2. Try making a prediction"
echo "3. If it works: ✅ You're done!"
echo ""
echo "========================================"
echo "Troubleshooting"
echo ""
echo "If still getting 'backend' error:"
echo "1. Check Railway logs (dashbaord → Deployments → View Logs)"
echo "2. Look for: '✓ Predictor initialized successfully'"
echo "3. Verify VITE_API_URL is set correctly (no trailing slash)"
echo "4. Wait 30 seconds and refresh your browser"
echo ""
echo "========================================"
